name: build-vitruvio

on: 
  push:
    branches:
      - main
      - develop
      - 'arisona/workflows'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Run UE build for Vitruvio
      - run: |
          echo "Yay. First run. On $GITHUB_WORKSPACE"


