name: build-vitruvio

on: 
  push:
    branches:
      - main
      - develop
      - 'arisona/workflows'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Yay. First run. On $env:GITHUB_WORKSPACE ${{github.workspace}}"
